---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne6_left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne6_right
